inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  Exclude:
    - test.rb
    - examples/**/*

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Check with yard instead.
Style/Documentation:
  Enabled: false
