#!/usr/bin/env ruby
# frozen_string_literal: true

# This static test file was generated by `brutal` using Brutal version 1.6.0.beta1.

require "simplecov"

::SimpleCov.command_name "Brutal test suite"
::SimpleCov.start

require "../../../lib/brutal/format"

# ------------------------------------------------------------------------------

actual = ::Brutal::Format::Ruby.new("# frozen_string_literal: true", "'Hello ' + '%<string>s'", ["%<subject>s.length"],
                                    **{ "string"=>%w[Alice Bob] })

raise if actual.combinations_values != [["Alice"], ["Bob"]]
raise if actual.context_names != ["string"]
raise if actual.contexts_values != [%w[Alice Bob]]
if actual.thematic_break_ruby_code != "# ------------------------------------------------------------------------------\n"
  raise
end
if actual.to_s != "# frozen_string_literal: true\n\n# ------------------------------------------------------------------------------\n\nactual = begin\n  'Hello ' + 'Alice'\nend\n\nraise if actual.length != 11\n\n# ------------------------------------------------------------------------------\n\nactual = begin\n  'Hello ' + 'Bob'\nend\n\nraise if actual.length != 9\n"
  raise
end

# ------------------------------------------------------------------------------

actual = ::Brutal::Format::Ruby.new("# frozen_string_literal: true", "'Hello ' + '%<string>s'", ["%<subject>s.to_s"],
                                    **{ "string"=>%w[Alice Bob] })

raise if actual.combinations_values != [["Alice"], ["Bob"]]
raise if actual.context_names != ["string"]
raise if actual.contexts_values != [%w[Alice Bob]]
if actual.thematic_break_ruby_code != "# ------------------------------------------------------------------------------\n"
  raise
end
if actual.to_s != "# frozen_string_literal: true\n\n# ------------------------------------------------------------------------------\n\nactual = begin\n  'Hello ' + 'Alice'\nend\n\nraise if actual.to_s != \"Hello Alice\"\n\n# ------------------------------------------------------------------------------\n\nactual = begin\n  'Hello ' + 'Bob'\nend\n\nraise if actual.to_s != \"Hello Bob\"\n"
  raise
end
