#!/usr/bin/env ruby
# frozen_string_literal: true

# This static test file was generated by `brutal` using Brutal version 1.6.0.beta2.

begin
  require_relative "../../../lib/brutal/format"
rescue ::LoadError
  require "../../../lib/brutal/format"
end

# ------------------------------------------------------------------------------

# Starting an example

actual = begin
  ::Brutal::Format::Ruby.new("# frozen_string_literal: true", "# Before example", "'Hello ' + '%{string}'", "# After example", "# End of test", *"%{subject}.length", **{"string"=>["Alice", "Bob"]})
end

# Finishing an example

raise if actual.context_names != ["string"]
raise if actual.contexts_values != [["Alice", "Bob"]]
raise if actual.combinations_values != [["Alice"], ["Bob"]]
raise if actual.thematic_break_code != "# ------------------------------------------------------------------------------\n"
raise if actual.to_s != "# frozen_string_literal: true\n\n# ------------------------------------------------------------------------------\n\n# Before example\n\nactual = begin\n  'Hello ' + 'Alice'\nend\n\n# After example\n\nraise if actual.length != 11\n\n# ------------------------------------------------------------------------------\n\n# Before example\n\nactual = begin\n  'Hello ' + 'Bob'\nend\n\n# After example\n\nraise if actual.length != 9\n\n# ------------------------------------------------------------------------------\n\n# End of test\n"

# ------------------------------------------------------------------------------

# Starting an example

actual = begin
  ::Brutal::Format::Ruby.new("# frozen_string_literal: true", "# Before example", "'Hello ' + '%{string}'", "# After example", "# End of test", *"%{subject}.to_s", **{"string"=>["Alice", "Bob"]})
end

# Finishing an example

raise if actual.context_names != ["string"]
raise if actual.contexts_values != [["Alice", "Bob"]]
raise if actual.combinations_values != [["Alice"], ["Bob"]]
raise if actual.thematic_break_code != "# ------------------------------------------------------------------------------\n"
raise if actual.to_s != "# frozen_string_literal: true\n\n# ------------------------------------------------------------------------------\n\n# Before example\n\nactual = begin\n  'Hello ' + 'Alice'\nend\n\n# After example\n\nraise if actual.to_s != \"Hello Alice\"\n\n# ------------------------------------------------------------------------------\n\n# Before example\n\nactual = begin\n  'Hello ' + 'Bob'\nend\n\n# After example\n\nraise if actual.to_s != \"Hello Bob\"\n\n# ------------------------------------------------------------------------------\n\n# End of test\n"

# ------------------------------------------------------------------------------

# End of the brutal test
