---
header: |
  # frozen_string_literal: false

  require 'spectus'
  include Spectus

front_object: |
  "foo"

subject: |
  begin
    it { %{front_object}.%{challenge} }.%{level} %{matcher}
  rescue ::Spectus::Result::Fail => e
    e
  end

variables:
  challenge:
    - "upcase"
    - "gsub!('f', 'b')"
    - "boom"
    - "empty?(4)"
  level:
    - "MUST"
    - "SHOULD"
    - "MAY"
    - "MUST_NOT"
    - "SHOULD_NOT"
    - "MUST!"
    - "SHOULD!"
    - "MAY!"
    - "MUST_NOT!"
    - "SHOULD_NOT!"
  matcher:
    - "raise_exception(NoMethodError)"
    - "raise_exception(ArgumentError)"
    - "eql('foo')"
    - "equal(42)"

actual_values:
  - "%{subject}.level"
  - "%{subject}.to_s"
  - "%{subject}.to_sym"
  - "%{subject}.error?"
  - "%{subject}.failure?"
  - "%{subject}.info?"
  - "%{subject}.negate?"
  - "%{subject}.failed?"
  - "%{subject}.passed?"
  - "%{subject}.success?"
  - "%{subject}.valid?"
  - "%{subject}.warning?"
  - "%{subject}.char"
  - "%{subject}.message"
  - "%{subject}.to_s"
  - "%{subject}.inspect"
  - "%{subject}.color('foo')"
  - "%{subject}.actual.class"
  - "%{subject}.error.class"
  - "%{subject}.got.class"
